application: nebulous-adventure
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: .*
  script: main.py

libraries:
- name: jinja2
  version: "2.6"
